### PR TITLE
Feature: Add destroy function that removes the plugin and its bindings

### PR DESCRIPTION
**Pull request by hinshun**
For issue #185

### CODE REVIEW

**Comment by smcclstocks** [comment]
would love to see this accepted. +1

**Comment by smcclstocks** [comment]
+1

**Comment by aemkei** [comment]
Not sure about `google.maps.event.clearInstanceListeners` because it might cause some side effects. But I'll merge it and hope it will work for you!

**Comment by cmwelsh** [comment]
> But I'll merge it and hope it will work for you!

It looks like you closed this pull request without merging... :)

**Comment by aemkei** [comment]
D'oh (x.x).

**Comment by hinshun** [comment]
@aemkei
I haven't encountered problems yet, but upon searching I found this related thread:
https://github.com/dylanfprice/angular-gm/issues/4

May be worth changing those clearInstanceListeners to that implementation.

**Comment by smcclstocks** [comment]
will you be bumping the version for bower folks

**Comment by aemkei** [comment]
@smcclstocks Done

**Comment by smcclstocks** [comment]
Thanks man.. appreciate it

**Pull request merged**
